### ISSUE TITLE
Support alternate file types (beyond .js)

### ISSUE THREAD

**Issue by mikeerickson** [oitozero/gulp-todoist#3]
From so far as I can tell, this plugin will only process .js files?   Would it be possible to expand to support really any text file type (including PHP, C/C#, HTML, etc)

**Comment by oitozero** [comment]
It should work with any file type. Just update the wildcard.

```
gulp.task('default', function () {
    return gulp.src('/**/*.php')
    .pipe(todoist());
});
```

Let me know if you have any issue.
